apiVersion: apps/v1
kind: Deployment
metadata:
  name: golangtester
spec:
  replicas: 3
  selector:
    matchLabels:
      name: golangtester
  template:
    metadata:
      labels:
        name: golangtester
    spec:
      containers:
      - image: kiranbabycontainerreg.azurecr.io/kiranbabycontainerrepo:golangtester
        name: kiranbabycontainerreg
        ports:
          - containerPort: 8081
      imagePullSecrets: 
      - name: golangtestersecret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: golangtester-service
spec:
  type: LoadBalancer
  selector:
    name: golangtester
  ports:
  - name: http  
    port: 80
    targetPort: 8081
